### ISSUE TITLE
Error: Undefined class constant &#039;MYSQL_ATTR_SSL_CA&#039; in Drush\Sql\Sqlmysql->creds()

### ISSUE THREAD

**Issue by SuperNami** [fourkitchens/emulsify#176]
After running `drush en unified_twig_ext` inside the emulsify folder I'm getting the following error:

```
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in /home/user/website/vendor/drush/drush/lib/Drush/Sql/Sqlmysql.php on line 56 #0 /home/user/website/vendor/drush/drush/lib/Drush/Sql/SqlBase.php(165): Drush\Sql\Sqlmysql->creds()
#1 /home/user/website/vendor/drush/drush/includes/environment.inc(393): Drush\Sql\SqlBase->query('SELECT 1;')
#2 /home/user/website/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(462): drush_valid_db_credentials()
#3 /home/user/website/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php(109): Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate()
#4 /home/user/website/vendor/drush/drush/includes/bootstrap.inc(430): Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate()
#5 /home/user/website/vendor/drush/drush/includes/bootstrap.inc(471): drush_bootstrap_validate(4)
#6 /home/user/website/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(6)
#7 /home/user/website/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /home/user/website/vendor/drush/drush/drush.php(12): drush_main()
#9 {main}
Error: Undefined class constant &#039;MYSQL_ATTR_SSL_CA&#039; in Drush\Sql\Sqlmysql->creds() (line 56 of /home/user/website/vendor/drush/drush/lib/Drush/Sql/Sqlmysql.php).
Drush command terminated abnormally due to an unrecoverable error.
```
I'm using the Drush executable from: https://github.com/drupal-composer/drupal-project

Any clue as what this might be?

**Comment by amazingrando** [comment]
@SuperNami I haven't seen this issue before. 

Please list out details of your system (Mac/Linux/Windows OS version; Drush version; and anything else relevant.) and the steps to reproduce this problem. This will help us troubleshoot the issue. Thanks!

**Comment by SuperNami** [comment]
I had to uncomment `extension=pdo_mysql` from [php.ini](https://github.com/php/php-src/blob/master/php.ini-production) and then the Drush issue disappeared.

However now I'm getting this error:
```
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
unified_twig_ext was not found.                                                                                                                                [warning]
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
No release history was found for the requested project (unified_twig_ext).                                                                                     [error]
```

The extension is downloaded with composer and is in the vendor folder: ![selection_091](https://user-images.githubusercontent.com/24568457/32726137-25a54e62-c878-11e7-8b36-3df4aa5ff00d.png)

Not sure on how to proceed.

**Comment by amazingrando** [comment]
@SuperNami I would start by troubleshooting Drush. If `drush version` is throwing errors, then whatever is going on there may impact the rest of the installation process.

Once you have the Drush problems sorted out we can revisit the issues with Emulsify.

**Comment by SuperNami** [comment]
Drush problem resolved when updating Drush to the latest version with composer: `composer global require drush/drush:dev-master`

But now when running `drush en unified_twig_ext` in the emulsify folder:
```
[user@pc emulsify]$ drush en unified_twig_ext
[error]  Unable to install modules unified_twig_ext due to missing modules unified_twig_ext.
```

**Comment by SuperNami** [comment]
I get it now, I was using the quickstart while I should have used the Drupal specific installation. Not sure how the quick start is supposed to work when it doesn't work with those modules enabled.

**Comment by amazingrando** [comment]
@SuperNami Glad that you got everything resolved! 👍

**Comment by evanmwillhite** [comment]
@amazingrando the README could maybe use some adjusting here. The Standalone quickstart instructions are for prototyping with Emulsify outside of any system (Drupal or otherwise), but the heading reads "Quickstart (Emulsify Standalone)." We could maybe tweak that to say something more clear.
