### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by micheljp** [fourkitchens/emulsify#270]
npm start is getting through the gulp instructions for the most part but then errs out. Any ideas?

`site generation took 1.8449749946594 seconds and used 22MB of memory...
my precious...
[21:02:57] Finished 'pl:full' after 1.88 s
[21:02:57] Starting 'compile'...
[21:02:57] Finished 'compile' after 3.82 μs
[21:03:00] Using gulpfile /var/www/public/drupal8.x/themes/custom/emulsify/gulpfile.js
[21:03:00] Starting 'css'...
[21:03:00] Starting 'scripts'...
[21:03:00] Finished 'scripts' after 2.35 ms
[21:03:00] Starting 'styleguide-scripts'...
[21:03:00] Finished 'styleguide-scripts' after 1.54 ms
[21:03:00] Starting 'watch:pl'...
[21:03:01] Finished 'watch:pl' after 276 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/concat-with-sourcemaps/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/concat-with-sourcemaps/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /var/www/public/drupal8.x/themes/custom/emulsify/node_modules/concat-with-sourcemaps/index.js:60:28
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/concat-with-sourcemaps/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Concat.add (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/concat-with-sourcemaps/index.js:58:18)
    at DestroyableTransform.bufferContents [as _transform] (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/gulp-concat/index.js:68:12)
    at DestroyableTransform.Transform._read (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/readable-stream/lib/_stream_writable.js:406:64)

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v6.11.3/bin/node" "/home/vagrant/.nvm/versions/node/v6.11.3/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 1`

**Comment by micheljp** [comment]
I did an npm update in the emulsify directory and after the update, I'm getting a new error:

`> emulsify@1.0.0 start /var/www/public/drupal8.x/themes/custom/emulsify
> gulp clean && gulp compile && gulp theme

/var/www/public/drupal8.x/themes/custom/emulsify/node_modules/emulsify-gulp/index.js:54
      )
      ^

SyntaxError: Unexpected token )`

**Comment by crashspringfield** [comment]
@micheljp What versions of Node/NPM are you using? The syntax error is coming from a trailing commas in function calls. Some people have had success upgrading to Node 8+.

Another option is to copy `emulsify-gulp/index.js` into your project and reference that instead of the one in the `node_modules` directory. You'll then be able to remove the commas yourself.

**Comment by micheljp** [comment]
Thanks all for the feedback.  I upgrade node to 8.3 and was able to successfully run it. It's getting through everything up to `serving files from ./` then it begins the imagemin process, where it's erring out again @
`[13:30:04] Starting 'imagemin'...
[13:30:04] Finished 'imagemin' after 530 μs

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Premature end of JPEG file`

I'm assuming this is a local issue with a certain jpg but have any of you seen this error? Thanks again.

**Comment by micheljp** [comment]
I was able to track down the offending image by installing `gulp-debug` and adding this to `emulsify-gulp/index.js`:
`const debug = require('gulp-debug')`

`  gulp.task('imagemin', () => {
    gulp
      .src(config.paths.img)
      .pipe(
        imagemin([
          imagemin.jpegtran({ progressive: true }),
          imagemin.svgo({
            plugins: [{ removeViewBox: false }, { cleanupIDs: false }],
          }),
        ]),
      )
      **### .pipe(debug(gulp.dest(file => file.base)));**
  });`

Is this worth putting in the repo?

**Comment by evanmwillhite** [comment]
@micheljp Sorry for the delay, but this seems like something we should look into. Do you mind pasting the error in here? I am not able to replicate locally. Thank you!

**Comment by evanmwillhite** [comment]
Closing due to inactivity.
