### ISSUE TITLE
Pa11y breaks npm start

### ISSUE THREAD

**Issue by adamfchs** [fourkitchens/emulsify#316]
To reproduce:
1. npm install 
2. npm start

Throws this error:
mytheme/node_modules/emulsify-gulp/gulp-tasks/pa11y.js:6
async function pa11yRun(pa11yUrl, config) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by evanmwillhite** [comment]
I tested against a new install and didn't see this error. I believe this might be a Node version issue based on some brief reading - I think `async` requires versions later than 7.6. 

I'm going to close but feel free to reopen and provide details if that is not the case. Thanks!

**Comment by adamfchs** [comment]
Thanks for the quick response!  Upgrading node.js did the trick—although I did also have to install pa11y and postcss as package dependencies in the my theme.  Seems to be working great now.

**Comment by evanmwillhite** [comment]
Awesome, thanks for posting your steps!
