### ISSUE TITLE
'npm start' throws errors

### ISSUE THREAD

**Issue by tanc** [fourkitchens/emulsify#6]
I have gulp is installed globally. After `npm install` runs successfully, running `npm start` throws:

```
npm start                                                                                                 >>>

> fourk@1.0.0 start ..../themes/custom/fsl_fourk
> gulp clean && gulp compile && gulp theme

[19:32:53] Local gulp not found in ..../themes/custom/fsl_fourk
[19:32:53] Try running: npm install gulp
```

If I install gulp locally with `npm install gulp` and then run `npm start` again I get:

```
npm start                                                                                                 >>>

> fourk@1.0.0 start ..../themes/custom/fsl_fourk
> gulp clean && gulp compile && gulp theme

module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-help'
```

**Comment by evanmwillhite** [comment]
Sorry for the delay @tanc - didn't realize I wasn't getting notifications on the repo. `gulp-help` is a dependency in https://github.com/fourkitchens/fourk-gulp (this is the where the gulp tasks are stored for this project and is installed as an npm package itself), so it looks like `npm install` might not have completed correctly after all. Can you try re-running that command and let me know if there are any warnings (or errors obviously) that occur that might be helpful? 

Here's a link to [the dependency in package.json](https://github.com/fourkitchens/fourk-gulp/blob/develop/package.json#L17). Also, I'm running gulp globally as well - shouldn't be an issue there.

**Comment by tanc** [comment]
hey no worries @evanmwillhite. Unfortunately I'm mid project now using Phase2's pattern lab starter as my base so I won't be able to test your one for a while. I'll try and come back to it and close off this issue soon.

I have other questions about Drupal and Pattern Lab, mostly around process that I'd love some input on from dev shops using it with success. Any chance you'd be interesting in chatting about it, maybe on [Gitter channel](https://gitter.im/pattern-lab/php)?

**Comment by evanmwillhite** [comment]
Sounds good @tanc. Phase2's is excellent - I actually referenced it as a baseline when creating this approach months ago. In fact, I plan on doing a write-up soon on the differences between the two to help folks decide which best suits their needs. 

I'm not on Gitter, but I know that there's a decent amount of conversation around this kind of thing in the drupaltwig.slack.com #components channel if that helps.

**Comment by amazingrando** [comment]
@tanc Just checking in with you to see if your issue is resolved so that we can close this issue. Thanks!

**Comment by jerseycheese** [comment]
@evanmwillhite @amazingrando 

Actually, I'm having this problem too after `npm install`.  I run `npm start`, which errors out and I get told to `npm install gulp` (which I do), and then errors about missing gulp-help and lodash and so on (for anything required in gulpfile.js)...

Here's what happens during my `npm install`:

```
Jacks-MacBook-Pro-3:emulsify-master advojack$ npm install
npm WARN package.json emulsify@1.0.0 No repository field.
npm WARN package.json emulsify@1.0.0 No license field.
npm WARN engine gulp-svg-sprite@1.3.6: wanted: {"node":">= 4.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine svg-sprite@1.3.6: wanted: {"node":">= 4.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine normalize-url@1.8.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated swig@1.4.0: This package is no longer maintained
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine request@2.78.0: wanted: {"node":">= 4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
-
> jpegtran-bin@3.2.0 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 
> optipng-bin@3.1.2 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
 
> gifsicle@3.0.4 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
 
> phantomjs-prebuilt@2.1.14 install /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.0.0 @ /usr/local/bin/phantomjs.
Download already available at /var/folders/sg/pnznnxm12238flm7329nj24r0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/sg/pnznnxm12238flm7329nj24r0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1482263910683/phantomjs-2.1.1-macosx -> /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-svg-sprite/node_modules/svg-sprite/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine string-width@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine string-width@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
\
> node-sass@3.13.1 install /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/advojack/.npm/node-sass/3.13.1/darwin-x64-14_binding.node

> node-sass@3.13.1 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node
Testing binary
Binary is fine

> fsevents@1.0.15 install /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.7","npm":"2.11.3"})
-
> ngrok@2.2.4 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master/node_modules/emulsify-gulp/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
ngrok - binary downloaded...
ngrok - binary unpacked.

> emulsify@1.0.0 postinstall /Applications/MAMP/htdocs/advostarterkit/themes/contrib/emulsify-master
> rm -rf pattern-lab && composer create-project pattern-lab/edition-twig-standard pattern-lab && rm -rf pattern-lab/source && ln -s ../components pattern-lab/source

Installing pattern-lab/edition-twig-standard (v2.2.1)
  - Installing pattern-lab/edition-twig-standard (v2.2.1)
    Loading from cache

Created project in pattern-lab
> PatternLab\Installer::setProjectInstall
> PatternLab\Installer::getSuggestedStarterKits
> PatternLab\Installer::getConfigOverrides
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing pattern-lab/styleguidekit-assets-default (v3.3.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing pattern-lab/styleguidekit-twig-default (v3.0.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing twig/twig (v1.29.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing symfony/yaml (v3.2.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing symfony/process (v3.2.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing symfony/finder (v3.2.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing symfony/filesystem (v3.2.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing symfony/event-dispatcher (v3.2.1)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing shudrum/array-finder (v1.1.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing seld/jsonlint (1.5.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing michelf/php-markdown (1.7.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing kevinlebrun/colors.php (1.0.2)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing doctrine/collections (v1.3.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing alchemy/zippy (0.3.5)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing pattern-lab/core (v2.7.0)
    Loading from cache

> PatternLab\Installer::postPackageInstall
  - Installing pattern-lab/patternengine-twig (v2.1.2)
    Loading from cache

> PatternLab\Installer::postPackageInstall
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter)
Writing lock file
Generating autoload files
> PatternLab\Installer::postUpdateCmd

suggested starterkits that work with this edition:

  1: pattern-lab/starterkit-twig-base
  2: pattern-lab/starterkit-twig-demo

choose an option or hit return to skip: (ex. 1) > 1

downloading the starterkit. this may take a few minutes...
finished downloading the starterkit...
installing the starterkit files...
starterkit files have been installed...
cleaning up the temp files...
the starterkit installation is complete...

Thank you for installing...

(                               (             
)\ )        )   )               )\ )         )
(()/(   ) ( /(( /(  (  (        (()/(    ) ( /(
/(_)| /( )\())\())))\ )(   (    /(_))( /( )\())
(_)) )(_)|_))(_))//((_|()\  )\ )(_))  )(_)|(_)\
| _ ((_)_| |_| |_(_))  ((_)_(_/(| |  ((_)_| |(_)
|  _/ _` |  _|  _/ -_)| '_| ' \)) |__/ _` | '_ \  
|_| \__,_|\__|\__\___||_| |_||_||____\__,_|_.__/  

emulsify-gulp@1.0.0 node_modules/emulsify-gulp
├── node-normalize-scss@1.4.0
├── minimist@1.1.3
├── del@2.2.2 (is-path-cwd@1.0.0, object-assign@4.1.0, pify@2.3.0, rimraf@2.5.4, pinkie-promise@2.0.1, is-path-in-cwd@1.0.0, globby@5.0.0)
├── gulp-help@1.6.1 (object-assign@3.0.0, chalk@1.1.3)
├── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
├── gulp-cached@1.1.1 (lodash.defaults@4.2.0, through2@2.0.3)
├── gulp-sass-glob@1.0.8 (slash@1.0.0, minimatch@3.0.3, through2@2.0.3)
├── breakpoint-sass@2.7.1
├── singularitygs@1.7.1
├── gulp-if@2.0.2 (gulp-match@1.0.3, through2@2.0.3, ternary-stream@2.0.1)
├── js-yaml@3.7.0 (esprima@2.7.3, argparse@1.0.9)
├── gulp-flatten@0.2.0 (through2@2.0.3, gulp-util@3.0.7)
├── gulp-plumber@1.1.0 (through2@2.0.3, gulp-util@3.0.7)
├── gulp-sourcemaps@1.9.1 (detect-newline@2.1.0, graceful-fs@4.1.11, convert-source-map@1.3.0, strip-bom@2.0.0, vinyl@1.2.0, debug-fabulous@0.0.4, through2@2.0.3, css@2.2.1, acorn@4.0.4, source-map@0.5.6)
├── gulp-concat@2.6.1 (vinyl@2.0.1, through2@2.0.3, concat-with-sourcemaps@1.0.4)
├── gulp-notify@2.2.0 (lodash.template@3.6.2, node.extend@1.1.6, through2@0.6.5, gulp-util@3.0.7)
├── gulp-clean-css@2.3.2 (object-assign@4.1.0, through2@2.0.3, gulp-util@3.0.7, vinyl-sourcemaps-apply@0.2.1, clean-css@3.4.23)
├── gulp@3.9.1 (interpret@1.0.1, pretty-hrtime@1.0.3, deprecated@0.0.1, archy@1.0.0, tildify@1.2.0, v8flags@2.0.11, chalk@1.1.3, semver@4.3.6, orchestrator@0.3.8, liftoff@2.3.0, gulp-util@3.0.7, vinyl-fs@0.3.14)
├── gulp-uglify@1.5.4 (uglify-save-license@0.4.1, deap@1.0.0, isobject@2.1.0, fancy-log@1.2.0, through2@2.0.3, gulp-util@3.0.7, vinyl-sourcemaps-apply@0.2.1, uglify-js@2.6.4)
├── gulp-imagemin@2.4.0 (object-assign@4.1.0, plur@2.1.2, chalk@1.1.3, through2-concurrent@1.1.1, pretty-bytes@2.0.1, gulp-util@3.0.7, imagemin@4.0.0)
├── lodash@3.10.1
├── node-notifier@4.6.1 (shellwords@0.1.0, semver@5.3.0, growly@1.3.0, which@1.2.12, lodash.clonedeep@3.0.2, cli-usage@0.1.4)
├── sassdoc@2.1.20 (strip-indent@1.0.1, glob2base@0.0.12, docopt@0.6.2, chalk@1.1.3, glob@5.0.15, vinyl-source-stream@1.1.0, safe-wipe@0.2.4, lodash.difference@3.2.2, minimatch@2.0.10, mkdirp@0.5.1, through2@0.6.5, concat-stream@1.6.0, lodash.uniq@3.2.2, sass-convert@0.5.2, multipipe@0.1.2, rimraf@2.5.4, update-notifier@0.3.2, scss-comment-parser@0.8.2, vinyl-fs@1.0.0, sassdoc-theme-default@2.4.3, babel-runtime@5.5.8)
├── gulp-svg-sprite@1.3.6 (vinyl@1.2.0, through2@2.0.3, gulp-util@3.0.7, svg-sprite@1.3.6)
├── gulp-eslint@2.1.0 (object-assign@4.1.0, bufferstreams@1.1.1, gulp-util@3.0.7, eslint@2.13.1)
├── gulp-sass@2.3.2 (lodash.clonedeep@4.5.0, through2@2.0.3, gulp-util@3.0.7, vinyl-sourcemaps-apply@0.2.1, node-sass@3.13.1)
├── psi@2.0.4 (prepend-http@1.0.4, object-assign@4.1.0, pify@2.3.0, pretty-bytes@3.0.1, pinkie-promise@2.0.1, chalk@1.1.3, repeating@2.0.1, sort-on@1.3.0, humanize-url@1.0.1, meow@3.7.0, update-notifier@0.6.3, download@4.4.3, lodash@4.17.2, googleapis@7.1.0)
├── gulp-autoprefixer@3.1.1 (through2@2.0.3, gulp-util@3.0.7, vinyl-sourcemaps-apply@0.2.1, postcss@5.2.6, autoprefixer@6.5.4)
├── gulp-sass-lint@1.3.2 (through2@2.0.3, gulp-util@3.0.7, sass-lint@1.10.2)
├── webpagetest@0.3.4 (entities@1.1.1, commander@2.9.0, csv@0.4.6, mocha@2.5.3, xml2js@0.4.17)
├── browser-sync@2.18.5 (server-destroy@1.0.1, emitter-steward@1.0.0, easy-extender@2.3.2, dev-ip@1.0.1, qs@6.2.1, browser-sync-client@2.4.4, http-proxy@1.15.2, opn@4.0.2, ua-parser-js@0.7.12, resp-modifier@6.0.2, serve-static@1.11.1, connect@3.5.0, fs-extra@1.0.0, eazy-logger@3.0.2, immutable@3.8.1, micromatch@2.3.11, socket.io@1.6.0, serve-index@1.8.0, yargs@6.4.0, localtunnel@1.8.2, bs-recipes@1.3.2, socket.io-client@1.6.0, portscanner@2.1.1, rx@4.1.0, browser-sync-ui@0.6.2, chokidar@1.6.1)
└── ngrok@2.2.4 (lock@0.1.3, xtend@4.0.1, uuid@3.0.1, async@0.9.2, decompress-zip@0.3.0, request@2.79.0)
```

Thanks for your work on this!  Have used Pattern Lab Starter on the past few projects, and I appreciate this slimmed-down alternate approach for D8+Pattern Lab.

**Comment by jerseycheese** [comment]
Also - after `npm install`ing manually the (missing) plugins, `npm start` shows the following, note the singularity error:
```
$ npm start

> emulsify@1.0.0 start /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify
> gulp clean && gulp compile && gulp theme

[15:23:27] Using gulpfile /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify/gulpfile.js
[15:23:27] Starting 'clean:docs:css'...
[15:23:27] Starting 'clean:css'...
[15:23:27] Finished 'clean:docs:css' after 8.75 ms
[15:23:27] Finished 'clean:css' after 6.06 ms
[15:23:27] Starting 'clean'...
[15:23:27] Finished 'clean' after 4.06 μs
[15:23:34] Using gulpfile /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify/gulpfile.js
[15:23:34] Starting 'docs:css'...
[15:23:34] Starting 'icons'...
[15:23:34] Starting 'pl:scss-to-json'...
[15:23:34] Finished 'pl:scss-to-json' after 3.13 ms
[15:23:34] Starting 'pl:full'...
configuring pattern lab...
[15:23:34] Finished 'icons' after 397 ms
[15:23:34] Finished 'docs:css' after 618 ms
your site has been generated...
site generation took 0.74351000785828 seconds and used 10MB of memory...
[15:23:35] Finished 'pl:full' after 932 ms
[15:23:35] Starting 'compile'...
[15:23:35] Finished 'compile' after 6.92 μs
[15:23:40] Using gulpfile /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify/gulpfile.js
[15:23:40] Starting 'css'...
[15:23:40] Starting 'scripts'...
[15:23:40] Starting 'styleguide-scripts'...
[15:23:40] Starting 'watch:pl'...
[15:23:41] Finished 'watch:pl' after 159 ms
Error in plugin 'sass'
Message:
    components/_patterns/style.scss
Error: File to import not found or unreadable: singularitygs/stylesheets/singularitygs
       Parent style sheet: /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify/components/_patterns/style.scss
        on line 5 of components/_patterns/style.scss
>> @import "singularitygs/stylesheets/singularitygs";
   ^

[15:23:41] gulp-notify: [CSS Error - Line 5] components/_patterns/style.scss
Error: File to import not found or unreadable: singularitygs/stylesheets/singularitygs
       Parent style sheet: /Applications/MAMP/htdocs/starterkit/themes/contrib/emulsify/components/_patterns/style.scss
        on line 5 of components/_patterns/style.scss
>> @import "singularitygs/stylesheets/singularitygs";
   ^

[15:23:41] Finished 'css' after 322 ms
[15:23:41] Finished 'scripts' after 305 ms
[15:23:41] Finished 'styleguide-scripts' after 310 ms
[15:23:41] Starting 'serve'...
[15:23:50] Finished 'serve' after 8.86 s
[15:23:50] Starting 'theme'...
[15:23:50] Finished 'theme' after 4.22 μs
[BS] Access URLs:
 ---------------------------------------------------------
       Local: http://localhost:3000/pattern-lab/public/
    External: http://192.168.0.21:3000/pattern-lab/public/
 ---------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.21:3001
 ---------------------------------------------------------
[BS] Serving files from: ./
```

**Comment by evanmwillhite** [comment]
@jerseycheese did you have Gulp installed globally before trying to install? It seems your installation process was interrupted somehow because of dependency issues, so it didn't install the remaining dependencies. In the 2nd comment, it looks like you're still missing one dependency (singularitygs). Try `npm install singularitygs` and rerun `npm start` to fix that one. Let me know if that doesn't fix it or better yet, if all of these problems go away once gulp is installed globally and you reinstall the project again. Thanks!

**Comment by jerseycheese** [comment]
@evanmwillhite 

Yes, I believe had gulp installed globally.  I definitely do now.

And yes, installing ```singularitygs``` manually did allow for ```npm start``` to do it's thing (which I had done previous to your reply to just to move things along).

Today, I've started over after removing the global gulp and reinstalling it globally (just to be sure). Downloaded a fresh copy of emulsify-master, ran ```npm install```ed and then ran ```npm start``` and I get this error:

```
$ npm start

> emulsify@1.0.0 start /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify
> gulp clean && gulp compile && gulp theme

[12:39:51] Using gulpfile /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/gulpfile.js
[12:39:51] Starting 'clean:docs:css'...
[12:39:51] Starting 'clean:css'...
[12:39:51] Finished 'clean:docs:css' after 8.7 ms
[12:39:51] Finished 'clean:css' after 6.86 ms
[12:39:51] Starting 'clean'...
[12:39:51] Finished 'clean' after 29 μs
[12:39:54] Using gulpfile /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/gulpfile.js
[12:39:54] Starting 'docs:css'...
[12:39:54] Starting 'icons'...
[12:39:54] Starting 'pl:scss-to-json'...
[12:39:54] Finished 'pl:scss-to-json' after 7.54 ms
[12:39:54] Starting 'pl:full'...
configuring pattern lab...
[12:39:55] Finished 'icons' after 437 ms
[12:39:55] Finished 'docs:css' after 830 ms
your site has been generated...
site generation took 0.97508001327515 seconds and used 10MB of memory...
mama always said life was like a box of chocolates. you never know what you're gonna get...
[12:39:55] Finished 'pl:full' after 1.13 s
[12:39:55] Starting 'compile'...
[12:39:55] Finished 'compile' after 2.76 μs
[12:39:58] Using gulpfile /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/gulpfile.js
[12:39:58] Starting 'css'...
[12:39:58] Starting 'scripts'...
[12:39:58] Starting 'styleguide-scripts'...
[12:39:58] Starting 'watch:pl'...
[12:39:58] Finished 'watch:pl' after 133 ms
[12:39:58] Finished 'scripts' after 244 ms
[12:39:58] Finished 'styleguide-scripts' after 249 ms
[12:39:59] Finished 'css' after 836 ms
[12:39:59] Starting 'serve'...
[12:40:02] Finished 'serve' after 3.62 s
[12:40:02] Starting 'theme'...
[12:40:02] Finished 'theme' after 3.19 μs
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at module.exports.plugin (/Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/node_modules/browser-sync/lib/server/index.js:36:25)
    at Object.startServer [as fn] (/Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/node_modules/browser-sync/lib/async.js:195:52)
    at /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/node_modules/browser-sync/lib/utils.js:276:13)
    at /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/node_modules/browser-sync/lib/utils.js:285:25

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/nvm/v6.9.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the emulsify@1.0.0 start script 'gulp clean && gulp compile && gulp theme'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the emulsify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean && gulp compile && gulp theme
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs emulsify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls emulsify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/nameofsite/themes/custom/emulsify/npm-debug.log
```

**Comment by jerseycheese** [comment]
@evanmwillhite Nevermind on my last comment ^ I learned that will happen if you already have the PL server running, which I did in a separate terminal window :P

**Comment by evanmwillhite** [comment]
Wow, thanks so much for the quick testing/reply @jerseycheese. Glad we got it sorted out, and let us know if you run into anything else along the way!

**Comment by mohammadpasha21** [comment]
I am trying to install emulsify on composer based Drupal project.
1. I could run composer require fourkitchens/emulsify
2.Enable Emulsify and its dependencies drush en emulsify components unified_twig_ext -y
At step 2  I get below error: 
![image](https://user-images.githubusercontent.com/18069289/37591577-033114e2-2b92-11e8-89ad-1de6c48c8cba.png)
